<?php

namespace app\admin\controller;

use app\admin\model\Admin;
use think\Request;
use app\admin\model\Admin as AdminModel;
class Index extends Common
{
	protected $admin;

	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->admin = new AdminModel();
	}


	public function index()
	{
		return $this->fetch();
	}

	public function list_r()
	{
		$param['limit'] = !empty($limit = input('limit')) ?: 5;
		$info           = $this->admin->getList($param);
		$this->assign('info', $info);
		return $this->fetch('list');
	}

	public function add(Request $res)
	{
		if ($res->isPost()) {
			$param	=	$res->param("");
			$exist =	 db('admin')->where('name',$param['name'])->count();
			if($exist){
				$this->error('该用户已存在！');
			}
			if ($this->admin->addAdmin($param)) {
				$this->jsAlert('添加成功', 'Index/list_r');
			} else {
				$this->error('添加失败！');
			}
		}
		return $this->fetch();
	}

	public function edit(Request $res)
	{
		$id   = input('id');
		$info = db('admin')->where('id', $id)->field('id,name')->find();
		if(empty($info)){
			 $this->error('该管理员不存在！');
		}
		if($res->isPost()){
			$param 	=	input('');
			if(empty($param['password'])){
				unset($param['password']);
			}else{
				$param['password']	=	md5($param['password']);
			}
			$res 	=	$this->admin->allowField(true)->save($param,['id'=>$id]);
			if($res !== false){
				$this->jsAlert('编辑成功', 'list_r');
			} else {
				$this->error('编辑失败！');
			}
		}else{
			$this->assign('info', $info);
			return $this->fetch('edit_admin');
		}
	}



	public function del(){
		$id 	= input('id');
		if(empty($id)){
			 $this->error('缺少参数！');
		}
		if(empty(AdminModel::get($id))){
			 $this->error('该管理员不存在！');
		}
		$res 	=	$this->admin->where('id',$id)->delete();
		if($res){
			$this->success('删除成功！', 'list_r');
		} else {
			$this->error('删除失败！');
		}
	}

	public function login()
	{
		if(request()->isPost()){
			$res	= $this->admin->login(input(''));
			if($res['code'] == 0){
				$this->jsAlert($res['msg'], 'index');
			}else{
				$this->jsAlert($res['msg'], 'login');
			}
		}else{
			return $this->fetch();
		}
	}

	public function logout(){
		if(session(null)===NULL){
			$this->jsAlert('退出成功！', 'login');
		}else{
			$this->jsAlert('退出失败！', 'javascript:history.back(-1);');
		}

	}

}
